import type { LevelConfig } from './types';

export const LEVEL_CONFIGS: LevelConfig[] = [
  {
    level: 1,
    title: 'Ibu Kota',
    subtitle: 'Capital City Basics',
    description: 'Learn about Banjarmasin and major cities in South Kalimantan.',
    type: 'multichoice',
    color: '#06b6d4',
    icon: '🏙️',
    requiredScore: 60,
    totalQuestions: 5,
  },
  {
    level: 2,
    title: 'Sungai & Alam',
    subtitle: 'Rivers & Nature',
    description: 'Discover the beautiful rivers and natural wonders of KalSel.',
    type: 'typing',
    color: '#10b981',
    icon: '🌊',
    requiredScore: 60,
    totalQuestions: 5,
  },
  {
    level: 3,
    title: 'Budaya Banjar',
    subtitle: 'Banjar Culture',
    description: 'Explore the rich Banjar culture, traditions and arts.',
    type: 'dragdrop',
    color: '#f59e0b',
    icon: '🎭',
    requiredScore: 60,
    totalQuestions: 5,
  },
  {
    level: 4,
    title: 'Kuliner Khas',
    subtitle: 'Traditional Cuisine',
    description: 'Identify the unique foods and dishes of South Kalimantan.',
    type: 'speech',
    color: '#ef4444',
    icon: '🍜',
    requiredScore: 60,
    totalQuestions: 5,
  },
  {
    level: 5,
    title: 'Sejarah KalSel',
    subtitle: 'Historical Facts',
    description: 'Test your knowledge of South Kalimantan history.',
    type: 'typing',
    color: '#8b5cf6',
    icon: '📜',
    requiredScore: 65,
    totalQuestions: 6,
  },
  {
    level: 6,
    title: 'Flora & Fauna',
    subtitle: 'Biodiversity',
    description: 'Match local plants and animals to their names.',
    type: 'dragdrop',
    color: '#84cc16',
    icon: '🌿',
    requiredScore: 65,
    totalQuestions: 6,
  },
  {
    level: 7,
    title: 'Pahlawan Lokal',
    subtitle: 'Local Heroes',
    description: 'Speak about KalSel heroes and historical figures.',
    type: 'speech',
    color: '#f97316',
    icon: '⚔️',
    requiredScore: 70,
    totalQuestions: 6,
  },
  {
    level: 8,
    title: 'Kerajinan Tangan',
    subtitle: 'Handicrafts',
    description: 'Arrange craft terms and identify traditional handicrafts.',
    type: 'dragdrop',
    color: '#ec4899',
    icon: '🎨',
    requiredScore: 70,
    totalQuestions: 6,
  },
  {
    level: 9,
    title: 'Geografi Lanjut',
    subtitle: 'Advanced Geography',
    description: 'Type precise answers about geography and districts.',
    type: 'typing',
    color: '#14b8a6',
    icon: '🗺️',
    requiredScore: 75,
    totalQuestions: 7,
  },
  {
    level: 10,
    title: 'Maestro KalSel',
    subtitle: 'Grand Master Challenge',
    description: 'Speak & prove you are a true expert on South Kalimantan!',
    type: 'speech',
    color: '#fbbf24',
    icon: '👑',
    requiredScore: 80,
    totalQuestions: 7,
  },
];
